# Generated by Django 5.0.6 on 2026-09-17 20:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('osm_tags', models.JSONField(default=list)),
                ('typical_margins_percent', models.FloatField(default=20.0)),
                ('capex_ratio', models.FloatField(default=0.6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('te', 'Telugu')], default='en', max_length=10)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('block', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rbi_serial_number', models.FloatField(blank=True, null=True, unique=True)),
                ('bank_name', models.CharField(db_index=True, max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['pincode'], name='core_app_ba_pincode_57acac_idx'), models.Index(fields=['latitude', 'longitude'], name='core_app_ba_latitud_a42ac3_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeasibilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('village_name', models.CharField(max_length=150)),
                ('block_name', models.CharField(max_length=150)),
                ('district_name', models.CharField(max_length=150)),
                ('center_lat', models.FloatField()),
                ('center_lng', models.FloatField()),
                ('margin_capital_available', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_project_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selected_scheme_tier', models.CharField(max_length=50)),
                ('interest_rate_pa', models.FloatField()),
                ('tenure_years', models.IntegerField()),
                ('moratorium_months', models.IntegerField()),
                ('amortization_schedule', models.JSONField(default=list)),
                ('competitor_count_5km', models.IntegerField(default=0)),
                ('competitor_count_10km', models.IntegerField(default=0)),
                ('estimated_market_saturation', models.CharField(max_length=50)),
                ('market_reach_summary', models.TextField(blank=True)),
                ('opportunity_analysis', models.JSONField(default=list)),
                ('swot_strengths', models.JSONField(default=list)),
                ('swot_weaknesses', models.JSONField(default=list)),
                ('swot_opportunities', models.JSONField(default=list)),
                ('swot_threats', models.JSONField(default=list)),
                ('localized_risks', models.JSONField(default=list)),
                ('suggested_pricing_strategy', models.JSONField(default=dict)),
                ('dpr_ready_summary', models.TextField(blank=True)),
                ('proposed_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.businesscategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalBusinessPOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('district', models.CharField(blank=True, max_length=100)),
                ('block', models.CharField(blank=True, max_length=100)),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('estimated_annual_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.businesscategory')),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='core_app_lo_latitud_f34bd7_idx')],
            },
        ),
    ]
